name: riemann
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.3
  - graph-tool
  - cudatoolkit=10.0
  - faiss-gpu
  - pytorch=1.3
  - pip
  - pip:
    - spell
    - absl-py==0.9.0
    - appnope==0.1.0
    - attrs==19.3.0
    - backcall==0.1.0
    - backports.shutil-get-terminal-size==1.0.0
    - bleach==3.1.5
    - cachetools==4.0.0
    - cairocffi==1.1.0
    - CairoSVG==2.4.2
    - certifi==2019.11.28
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.1.1
    - colorama==0.4.3
    - configparser==5.0.0
    - coverage==5.0.3
    - cssselect2==0.3.0
    - cursor==1.3.4
    - cycler==0.10.0
    - Cython==0.29.14
    - decorator==4.4.2
    - defusedxml==0.6.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - drawSvg==1.5.3
    - entrypoints==0.3
    - future==0.18.2
    - gitdb2==2.0.6
    - GitPython==3.0.5
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - gql==0.2.0
    - graphql-core==1.1
    - grpcio==1.26.0
    - h5py==2.10.0
    - halo==0.0.28
    - hyperbolic==1.1
    - idna==2.8
    - imageio==2.8.0
    - importlib-metadata==1.6.0
    - ipaddress==1.0.23
    - ipykernel==5.2.1
    - ipython==7.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.0
    - Jinja2==2.11.2
    - joblib==0.14.1
    - jsonpickle==1.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - jupyterthemes==0.20.0
    - kiwisolver==1.2.0
    - langcodes==1.4.1
    - lark-parser==0.8.5
    - lesscpy==0.14.0
    - log-symbols==0.0.14
    - marisa-trie==0.7.5
    - Markdown==3.1.1
    - MarkupSafe==1.1.1
    - matplotlib==3.2.1
    - mistune==0.8.4
    - msgpack==1.0.0
    - multipledispatch==0.6.0
    - munch==2.5.0
    - mypy==0.720
    - mypy-extensions==0.4.3
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - nltk==3.4.5
    - notebook==6.0.3
    - numpy==1.18.1
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - ordered-set==3.1.1
    - packaging==20.1
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - Pillow==7.1.2
    - ply==3.11
    - prometheus-client==0.7.1
    - promise==2.3
    - prompt-toolkit==3.0.5
    - protobuf==3.11.2
    - psutil==5.7.0
    - ptyprocess==0.6.0
    - py==1.8.1
    - py-cpuinfo==5.0.0
    - pyaml==20.4.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pycryptodomex==3.9.7
    - Pygments==2.6.1
    - pyparsing==2.4.6
    - pyrr==0.10.3
    - pyrsistent==0.16.0
    - pytest==3.0.7
    - pytest-cov==2.4.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - PyYAML==5.1.2
    - pyzmq==19.0.0
    - qtconsole==4.7.3
    - QtPy==1.9.0
    - regex==2018.2.21
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - requirements-parser==0.2.0
    - rsa==4.0
    - sacred==0.8.1
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - Send2Trash==1.5.0
    - sentry-sdk==0.14.3
    - shortuuid==1.0.1
    - six==1.14.0
    - smmap2==2.0.5
    - spell==0.37.2
    - spinners==0.0.24
    - subprocess32==3.5.4
    - svgwrite==1.4
    - tabulate==0.8.7
    - tensorboard==2.1.1
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - tinycss2==1.0.2
    - toml==0.9.6
    - tornado==6.0.4
    - tqdm==4.32.2
    - traitlets==4.3.3
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.1
    - Unidecode==1.1.1
    - urllib3==1.25.8
    - wandb==0.8.36
    - watchdog==0.10.2
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - Werkzeug==0.16.1
    - widgetsnbextension==3.5.1
    - wordfreq==2.2.2
    - wrapt==1.11.2
    - zipp==3.1.0
    - git+https://github.com/arunchaganty/embedding_evaluation.git#egg=embedding_evaluation
